openapi: 3.0.0
info:
  title: Addresses
  version: '1.0'
  description: |-
    # What are Addresses?
    Addresses represent one of the many shipping locations a customer can have. An address is created when a customer purchases a subscription. [Subscriptions](https://recharge.stoplight.io/docs/shop-docs/docs/subscriptions.md) are tied to a given address. Each customer can have multiple address objects in a many-to-one relationship. You can override shipping rates using this endpoint.
servers:
  - url: 'https://api.rechargeapps.com/addresses'
paths:
  '':
    get:
      summary: List addresses
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  addresses:
                    type: array
                    items: {}
              examples:
                Example:
                  value:
                    addresses:
                      - address1: 1234 Main St
                        address2: ''
                        city: Austin
                        company: ReCharge
                        country: United States
                        created_at: '2020-12-08T15:36:48'
                        customer_id: 51659309
                        discounts: []
                        first_name: Mikaela
                        id: 58968398
                        last_name: Rodriguez
                        note_attributes:
                          - name: Test
                            value: value
                        order_note: Test note
                        phone: '5551234567'
                        province: TX
                        shipping_lines_override: []
                        updated_at: '2021-03-07T20:20:44'
                        zip: '78704'
                      - address1: 1776 Washington Street
                        address2: ''
                        city: Los Angeles
                        company: ReCharge
                        country: United States
                        created_at: '2020-12-08T15:31:51'
                        customer_id: 51659309
                        discounts: []
                        first_name: John
                        id: 58968100
                        last_name: Doe
                        note_attributes: null
                        order_note: null
                        phone: '5551234567'
                        province: California
                        shipping_lines_override: []
                        updated_at: '2020-12-08T15:31:51'
                        zip: '90404'
      operationId: get-addresses
      description: Retrieves a list of addresses tied to a ReCharge store.
    post:
      summary: Create an address
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Address'
              examples:
                Example:
                  value:
                    address:
                      id: 42171447
                      customer_id: 37657002
                      address1: 1030 Barnum Ave
                      address2: Suite 101
                      city: Stratford
                      company: Fake Company
                      country: United States
                      created_at: '2020-02-19T17:40:09'
                      discounts:
                        - id: 123456
                        - id: 788901
                      first_name: Fake First
                      last_name: Fake Last
                      note_attributes:
                        - name: custom name
                          value: custom value
                      order_note: My recurring order note
                      phone: 999-999-9999
                      province: Connecticut
                      shipping_lines_override:
                        - code: Standard Shipping
                          price: '0.00'
                          title: Standard Shipping
                      updated_at: '2020-12-17T18:50:27'
                      zip: '06614'
      operationId: post-addresses
      description: Creates a new address for a customer.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Address-Request'
            examples: {}
          application/xml:
            schema:
              type: object
              properties: {}
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Address'
        description: ''
    parameters: []
  '/:id':
    get:
      summary: Retrieve an address
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Address'
              examples: {}
      operationId: get-id
      description: Retrieves address for a customer based on ID.
    put:
      summary: Update an address
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Address'
      operationId: put-id
      description: Updates the specified address.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Address-Request'
    delete:
      summary: Delete an address
      tags: []
      responses:
        '204':
          description: No Content
      operationId: delete-id
      description: Deletes the specified address.
    parameters: []
  /count:
    get:
      summary: Count addresses
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  count:
                    type: integer
              examples:
                Example:
                  value:
                    count: 2
      operationId: get-count
      description: Retrieves a count of addresses.
      parameters:
        - schema:
            type: string
          in: query
          name: created_at_max
          description: Returns the count of addresses created before the given time.
        - schema:
            type: string
          in: query
          name: created_at_min
          description: Returns the count of addresses created after the given time.
        - schema:
            type: string
          in: query
          name: 'discount_code '
          description: Returns the count of addresses that have the provided discount_code applied.
        - schema:
            type: string
          in: query
          name: discount_id
          description: Returns the count of addresses that have the provided discount_id applied.
        - schema:
            type: string
          in: query
          name: updated_at_max
          description: Returns the count of addresses updated before the given date.
        - schema:
            type: string
          in: query
          name: updated_at_min
          description: Returns the count of addresses updated after the given time.
  /validate:
    post:
      summary: Validate an address
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  address1:
                    type: string
                    minLength: 1
                  city:
                    type: string
                    minLength: 1
                  errors:
                    type: object
                    properties: {}
                    required: []
                  state:
                    type: string
                    minLength: 1
                  state_name:
                    type: string
                    minLength: 1
                  zipcode:
                    type: string
                    minLength: 1
                required:
                  - address1
                  - city
                  - errors
                  - state
                  - state_name
                  - zipcode
              examples:
                Example:
                  value:
                    address1: 100 Main St
                    city: santa monica
                    errors: {}
                    state: CA
                    state_name: California
                    zipcode: '90404'
      operationId: post-validate
      description: |-
        Checks if an address is valid.

        **NOTE:** Address validation only works with United States addresses. At this time we do not validate the `address1` attribute.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Validate-Address'
components:
  schemas:
    Address:
      description: ''
      type: object
      x-examples: {}
      title: ''
      properties:
        address:
          type: object
          properties:
            id:
              type: integer
              description: Unique numeric identifier for the address.
            customer_id:
              type: integer
              description: Unique numeric identifier for the customer associated with the address.
            address1:
              type: string
              minLength: 1
              description: The street associated with the address.
            address2:
              type: string
              minLength: 1
              description: Any additional information associated with the address.
            city:
              type: string
              minLength: 1
              description: The city associated with the address.
            company:
              type: string
              minLength: 1
              description: The company associated with the address.
            country:
              type: string
              minLength: 1
              description: The country associated with the address.
            created_at:
              type: string
              minLength: 1
              description: The date and time when the address was created.
            discounts:
              type: array
              uniqueItems: true
              minItems: 1
              items:
                type: object
                properties:
                  id:
                    type: integer
                    description: Id of the discount you want to apply to an address.
            first_name:
              type: string
              minLength: 1
              description: The customer’s first name associated with the address. Minimum length is 1 character.
            last_name:
              type: string
              minLength: 1
              description: The customer’s last name associated with the address. Minimum length is 1 character.
            note_attributes:
              type: array
              uniqueItems: true
              minItems: 1
              description: Array of key-value pairs.
              items:
                type: object
                properties:
                  name:
                    type: string
                    minLength: 1
                  value:
                    type: string
                    minLength: 1
            order_note:
              type: string
              minLength: 1
              description: Notes added to all orders associated with the address.
            phone:
              type: string
              minLength: 1
              description: The phone number associated with the address. Required based on store settings.
            province:
              type: string
              minLength: 1
              description: The state or province associated to address. Check if country requires a province COUNTRIES_REQUIRING_PROVINCE.
            shipping_lines_override:
              type: array
              uniqueItems: true
              minItems: 1
              description: Used when shipping rates need to be overridden.
              items:
                type: object
                properties:
                  code:
                    type: string
                    minLength: 1
                  price:
                    type: string
                    minLength: 1
                  title:
                    type: string
                    minLength: 1
            updated_at:
              type: string
              minLength: 1
              description: The date and time when the address was last updated.
            zip:
              type: string
              minLength: 1
              description: Zip code of the street address. Required based on country.
          required:
            - customer_id
            - address1
            - city
            - country
            - province
    Address-Request:
      description: ''
      type: object
      properties:
        address1:
          type: string
          minLength: 1
          description: The street associated with the address.
        address2:
          type: string
          minLength: 1
          description: Any additional information associated with the address.
        city:
          type: string
          minLength: 1
          description: The city associated with the address.
        company:
          type: string
          minLength: 1
          description: The company associated with the address.
        country:
          type: string
          minLength: 1
          description: The country associated with the address.
        discounts:
          type: array
          uniqueItems: true
          minItems: 1
          items:
            type: object
            properties:
              id:
                type: integer
                description: Id of the discount you want to apply to an address.
            required:
              - id
        first_name:
          type: string
          minLength: 1
          description: The customer’s first name associated with the address. Minimum length is 1 character.
        last_name:
          type: string
          minLength: 1
          description: The customer’s last name associated with the address. Minimum length is 1 character.
        note_attributes:
          type: array
          uniqueItems: true
          minItems: 1
          description: Array of key-value pairs.
          items:
            type: object
            properties:
              name:
                type: string
                minLength: 1
              value:
                type: string
                minLength: 1
        order_note:
          type: string
          minLength: 1
          description: Notes added to all orders associated with the address.
        phone:
          type: string
          minLength: 1
          description: The phone number associated with the address. Required based on store settings.
        province:
          type: string
          minLength: 1
          description: The state or province associated to address. Check if country requires a province COUNTRIES_REQUIRING_PROVINCE.
        shipping_lines_override:
          type: array
          uniqueItems: true
          minItems: 1
          description: Used when shipping rates need to be overridden.
          items:
            type: object
            properties:
              code:
                type: string
                minLength: 1
              price:
                type: string
                minLength: 1
              title:
                type: string
                minLength: 1
        zip:
          type: string
          minLength: 1
          description: Zip code of the street address. Required based on country.
      required:
        - address1
        - city
        - country
        - province
    Validate-Address:
      description: ''
      type: object
      properties:
        address1:
          type: string
          minLength: 1
        city:
          type: string
          minLength: 1
        state:
          type: string
          minLength: 1
        zipcode:
          type: string
          minLength: 1
      required:
        - address1
        - state
        - zipcode
        - city
  responses: {}
